name: Simple PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  yaml-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint YAML files
        run: |
          sudo apt-get install -y yamllint
          yamllint .
