apiVersion: v1
kind: Secret
metadata:
  name: argocd-redis
  namespace: default
type: Opaque
data:
  redis-secrets.json: ewogICJQQVNTV09SRCI6ICJzdXBlci1zZWNyZXQtcGFzc3dvcmQiLAogICJVU0VSTkFNRSI6ICJyZWRpcy1hZG1pbiIsCiAgIlNFTlRJTkVMX1VTRVJOQU1FIjogInNlbnRpbmVsLXVzZXIiLAogICJTRU5USU5FTF9QQVNTV09SRCI6ICJzZW50aW5lbC1zZWNyZXQiCn0K
