apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-creds
              mountPath: /etc/redis-creds # Mount the secret as a file
              readOnly: true
          env:
            - name: REDIS_CREDS_FILE_PATH
              value: /etc/redis-creds/redis-creds.json # Set the file path as an environment variable
      volumes:
        - name: redis-creds
          secret:
            secretName: redis-creds-secret
